name: Publish to PyPI

on:
  push:
    paths:
      - labs/pyproject.toml

jobs:
  publish_to_pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install build dependencies
        run: python -m pip install --upgrade setuptools wheel build
      - name: Build the package
        run: python -m build labs/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: labs/dist/
          skip-existing: true
